cafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('meals/', include('meals.urls', namespace='meals')),
    path('reserve_table/', include('reservation.urls', namespace='reservation')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meals/urls.py
from django.urls import path
from . import views

app_name = 'meals'

urlpatterns = [
    path('', views.meal_list, name='meal_list'),
    path('<slug:slug>', views.meal_detail, name='meal_detail'), 
]

reservation/urls.py
from django.urls import path
from . import views

app_name = 'reservation'

urlpatterns = [
    path('', views.reserve_table, name='reserve_table'),
]

aboutus/models.py
from django.db import models

# Create your models here.

meals/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.

class Meals(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    people = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    preparation_time = models.IntegerField()
    image = models.ImageField(upload_to='meals/')
    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Meals, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'meal'
        verbose_name_plural = 'meals'

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    

reservation/models.py
from django.db import models

# Create your models here.

class Reservation(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.IntegerField()
    number_of_persons = models.IntegerField()
    date = models.DateField()   
    time = models.TimeField()

    def __str__(self):
        return self.name

reservation/forms.py
from django import forms 
from .models import Reservation

class ReserveTableForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'

aboutus/views.py
from django.shortcuts import render

# Create your views here.

meals/views.py
from django.shortcuts import render
from .models import Meals, Category

# Create your views here.

def meal_list(request):
    meal_list = Meals.objects.all()
    categories = Category.objects.all()
    context = {
        'meal_list': meal_list ,
        'categories': categories ,
    }
    return render(request, 'Meals/list.html', context)

def meal_detail(request, slug):
    meal_detail = Meals.objects.get(slug=slug)
    context = {'meal_detail': meal_detail}
    return render(request, 'Meals/detail.html', context)

reservation/views.py
from django.shortcuts import render

from .forms import ReserveTableForm
from .models import Reservation

# Create your views here.

def reserve_table(request):
    reserve_form = ReserveTableForm()

    if request.method == 'POST':
        reserve_form = ReserveTableForm(request.POST)

        if reserve_form.is_valid():
            reserve_form.save()

    context = {'form': reserve_form }
    return render(request, 'Reservation/reservation.html', context)

meals/templates/Meals/detail.html
{% extends 'base.html' %}

{% block body %}
    <section class="ftco-section">
    	<div class="container-fluid px-4">
    		<div class="row justify-content-center mb-5 pb-2">
          <div class="col-md-7 text-center heading-section ftco-animate">
          	<span class="subheading">Specialties</span>
            <h2 class="mb-4">Our Menu</h2>


            <img class="meal_img" src="{{meal_detail.image.url}}" alt="">
            <h2>{{meal_detail}}</h2>  
            <p>{{meal_detail.description}}</p> 

            <p>For : {{meal_detail.people}} People</p>
            <p>Preparation Time : {{meal_detail.preparation_time}} minutes</p>
            <p>Price : Rs. {{meal_detail.price}} </p>
         

          </div>
        </div>

    	</div>
	</section>

	{% comment %}

	<section class="ftco-section ftco-no-pt ftco-no-pb">
		<div class="container-fluid px-0">
			<div class="row no-gutters">
				<div class="col-md">
					<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url(images/insta-1.jpg);">
						<span class="ion-logo-instagram"></span>
					</a>
				</div>
				<div class="col-md">
					<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url(images/insta-2.jpg);">
						<span class="ion-logo-instagram"></span>
					</a>
				</div>
				<div class="col-md">
					<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url(images/insta-3.jpg);">
						<span class="ion-logo-instagram"></span>
					</a>
				</div>
				<div class="col-md">
					<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url(images/insta-4.jpg);">
						<span class="ion-logo-instagram"></span>
					</a>
				</div>
				<div class="col-md">
					<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url(images/insta-5.jpg);">
						<span class="ion-logo-instagram"></span>
					</a>
				</div>
			</div>
		</div>
	</section>

<footer class="ftco-footer ftco-bg-dark ftco-section">
  <div class="container-fluid px-md-5 px-3">
	<div class="row mb-5">
	  <div class="col-md-6 col-lg-3">
		<div class="ftco-footer-widget mb-4">
		  <h2 class="ftco-heading-2">Appetizer</h2>
		  <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
		  <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
			<li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
			<li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
			<li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
		  </ul>
		</div>
	  </div>
	  <div class="col-md-6 col-lg-3">
		<div class="ftco-footer-widget mb-4">
		  <h2 class="ftco-heading-2">Open Hours</h2>
		  <ul class="list-unstyled open-hours">
			<li class="d-flex"><span>Monday</span><span>9:00 - 24:00</span></li>
			<li class="d-flex"><span>Tuesday</span><span>9:00 - 24:00</span></li>
			<li class="d-flex"><span>Wednesday</span><span>9:00 - 24:00</span></li>
			<li class="d-flex"><span>Thursday</span><span>9:00 - 24:00</span></li>
			<li class="d-flex"><span>Friday</span><span>9:00 - 02:00</span></li>
			<li class="d-flex"><span>Saturday</span><span>9:00 - 02:00</span></li>
			<li class="d-flex"><span>Sunday</span><span> 9:00 - 02:00</span></li>
		  </ul>
		</div>
	  </div>
	  <div class="col-md-6 col-lg-3">
		<div class="ftco-footer-widget mb-4">
			<h2 class="ftco-heading-2">Newsletter</h2>
			<p>Far far away, behind the word mountains, far from the countries.</p>
		  <form action="#" class="subscribe-form">
			<div class="form-group">
			  <input type="text" class="form-control mb-2 text-center" placeholder="Enter email address">
			  <input type="submit" value="Subscribe" class="form-control submit px-3">
			</div>
		  </form>
		</div>
	  </div>
	  <div class="col-md-6 col-lg-3">
		 <div class="ftco-footer-widget mb-4">
		  <h2 class="ftco-heading-2">Instagram</h2>
		  <div class="thumb d-sm-flex">
				<a href="#" class="thumb-menu img" style="background-image: url(images/insta-1.jpg);">
				</a>
				<a href="#" class="thumb-menu img" style="background-image: url(images/insta-2.jpg);">
				</a>
				<a href="#" class="thumb-menu img" style="background-image: url(images/insta-3.jpg);">
				</a>
			</div>
			<div class="thumb d-flex">
				<a href="#" class="thumb-menu img" style="background-image: url(images/insta-4.jpg);">
				</a>
				<a href="#" class="thumb-menu img" style="background-image: url(images/insta-5.jpg);">
				</a>
				<a href="#" class="thumb-menu img" style="background-image: url(images/insta-6.jpg);">
				</a>
			</div>
		</div>
	  </div>
	</div>
	<div class="row">
	  <div class="col-md-12 text-center">

		<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
	  </div>
	</div>
  </div>
</footer>

{% endcomment %}

{% endblock %}

meals/templates/Meals/list.html
{% extends 'base.html' %}

{% block body %}
		<!-- Menu starts here -->
    <section class="ftco-section">
    	<div class="container-fluid px-4">
    		<div class="row justify-content-center mb-5 pb-2">
          <div class="col-md-7 text-center heading-section ftco-animate">
          	<span class="subheading">Specialties</span>
            <h2 class="mb-4">Our Menu</h2>
          </div>
        </div>
        <div class="row">

			{% for category in categories %}

        	<div class="col-md-6 col-lg-4 menu-wrap">
        		<div class="heading-menu text-center ftco-animate">
        			<h3>{{category}}</h3>
				</div>
				

				{% for meal in meal_list %}
				{% if meal.category == category %}
					<div class="menus d-flex ftco-animate">
				<div class="menu-img img" style="background-image: url(images/breakfast-1.jpg);"></div>
				<div class="text">
					<div class="d-flex">
						<div class="one-half">
							<h3><a href="{% url 'meals:meal_detail' meal.slug %}">{{meal.name}}</a></h3>
						</div>
						<div class="one-forth">
						<span class="price">{{meal.price}}</span>
						</div>
					</div>
					<p>{{meal.description}}</p>
				</div>
					</div>
				{% endif %}
				{% endfor %}
			

			</div>
			
			{% endfor %}

{% comment %}
        	<div class="col-md-6 col-lg-4 menu-wrap">
        		<div class="heading-menu text-center ftco-animate">
        			<h3>Lunch</h3>
        		</div>
        		<div class="menus d-flex ftco-animate">
              <div class="menu-img img" style="background-image: url(images/lunch-1.jpg);"></div>
              <div class="text">
              	<div class="d-flex">
	                <div class="one-half">
	                  <h3>Grilled Beef with potatoes</h3>
	                </div>
	                <div class="one-forth">
	                  <span class="price">$29</span>
	                </div>
	              </div>
	              <p><span>Meat</span>, <span>Potatoes</span>, <span>Rice</span>, <span>Tomatoe</span></p>
              </div>
            </div>
            <div class="menus d-flex ftco-animate">
              <div class="menu-img img" style="background-image: url(images/lunch-2.jpg);"></div>
              <div class="text">
              	<div class="d-flex">
	                <div class="one-half">
	                  <h3>Grilled Crab with Onion</h3>
	                </div>
	                <div class="one-forth">
	                  <span class="price">$29</span>
	                </div>
	              </div>
	              <p><span>Meat</span>, <span>Potatoes</span>, <span>Rice</span>, <span>Tomatoe</span></p>
              </div>
            </div>
            <div class="menus d-flex ftco-animate">
              <div class="menu-img img" style="background-image: url(images/lunch-3.jpg);"></div>
              <div class="text">
              	<div class="d-flex">
	                <div class="one-half">
	                  <h3>Grilled Crab with Onion</h3>
	                </div>
	                <div class="one-forth">
	                  <span class="price">$29</span>
	                </div>
	              </div>
	              <p><span>Meat</span>, <span>Potatoes</span>, <span>Rice</span>, <span>Tomatoe</span></p>
              </div>
            </div>
        	</div>

        	<div class="col-md-6 col-lg-4 menu-wrap">
        		<div class="heading-menu text-center ftco-animate">
        			<h3>Dinner</h3>
        		</div>
        		<div class="menus d-flex ftco-animate">
              <div class="menu-img img" style="background-image: url(images/dinner-1.jpg);"></div>
              <div class="text">
              	<div class="d-flex">
	                <div class="one-half">
	                  <h3>Grilled Beef with potatoes</h3>
	                </div>
	                <div class="one-forth">
	                  <span class="price">$29</span>
	                </div>
	              </div>
	              <p><span>Meat</span>, <span>Potatoes</span>, <span>Rice</span>, <span>Tomatoe</span></p>
              </div>
            </div>
            <div class="menus d-flex ftco-animate">
              <div class="menu-img img" style="background-image: url(images/dinner-2.jpg);"></div>
              <div class="text">
              	<div class="d-flex">
	                <div class="one-half">
	                  <h3>Grilled Crab with Onion</h3>
	                </div>
	                <div class="one-forth">
	                  <span class="price">$29</span>
	                </div>
	              </div>
	              <p><span>Meat</span>, <span>Potatoes</span>, <span>Rice</span>, <span>Tomatoe</span></p>
              </div>
            </div>
            <div class="menus d-flex ftco-animate">
              <div class="menu-img img" style="background-image: url(images/dinner-3.jpg);"></div>
              <div class="text">
              	<div class="d-flex">
	                <div class="one-half">
	                  <h3>Grilled Crab with Onion</h3>
	                </div>
	                <div class="one-forth">
	                  <span class="price">$29</span>
	                </div>
	              </div>
	              <p><span>Meat</span>, <span>Potatoes</span>, <span>Rice</span>, <span>Tomatoe</span></p>
              </div>
            </div>
        	</div>
{% endcomment %}


        </div>
    	</div>
	</section>

	{% comment %}

	<section class="ftco-section ftco-no-pt ftco-no-pb">
		<div class="container-fluid px-0">
			<div class="row no-gutters">
				<div class="col-md">
					<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url(images/insta-1.jpg);">
						<span class="ion-logo-instagram"></span>
					</a>
				</div>
				<div class="col-md">
					<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url(images/insta-2.jpg);">
						<span class="ion-logo-instagram"></span>
					</a>
				</div>
				<div class="col-md">
					<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url(images/insta-3.jpg);">
						<span class="ion-logo-instagram"></span>
					</a>
				</div>
				<div class="col-md">
					<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url(images/insta-4.jpg);">
						<span class="ion-logo-instagram"></span>
					</a>
				</div>
				<div class="col-md">
					<a href="#" class="instagram img d-flex align-items-center justify-content-center" style="background-image: url(images/insta-5.jpg);">
						<span class="ion-logo-instagram"></span>
					</a>
				</div>
			</div>
		</div>
	</section>

<footer class="ftco-footer ftco-bg-dark ftco-section">
  <div class="container-fluid px-md-5 px-3">
	<div class="row mb-5">
	  <div class="col-md-6 col-lg-3">
		<div class="ftco-footer-widget mb-4">
		  <h2 class="ftco-heading-2">Appetizer</h2>
		  <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
		  <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
			<li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
			<li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
			<li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
		  </ul>
		</div>
	  </div>
	  <div class="col-md-6 col-lg-3">
		<div class="ftco-footer-widget mb-4">
		  <h2 class="ftco-heading-2">Open Hours</h2>
		  <ul class="list-unstyled open-hours">
			<li class="d-flex"><span>Monday</span><span>9:00 - 24:00</span></li>
			<li class="d-flex"><span>Tuesday</span><span>9:00 - 24:00</span></li>
			<li class="d-flex"><span>Wednesday</span><span>9:00 - 24:00</span></li>
			<li class="d-flex"><span>Thursday</span><span>9:00 - 24:00</span></li>
			<li class="d-flex"><span>Friday</span><span>9:00 - 02:00</span></li>
			<li class="d-flex"><span>Saturday</span><span>9:00 - 02:00</span></li>
			<li class="d-flex"><span>Sunday</span><span> 9:00 - 02:00</span></li>
		  </ul>
		</div>
	  </div>
	  <div class="col-md-6 col-lg-3">
		<div class="ftco-footer-widget mb-4">
			<h2 class="ftco-heading-2">Newsletter</h2>
			<p>Far far away, behind the word mountains, far from the countries.</p>
		  <form action="#" class="subscribe-form">
			<div class="form-group">
			  <input type="text" class="form-control mb-2 text-center" placeholder="Enter email address">
			  <input type="submit" value="Subscribe" class="form-control submit px-3">
			</div>
		  </form>
		</div>
	  </div>
	  <div class="col-md-6 col-lg-3">
		 <div class="ftco-footer-widget mb-4">
		  <h2 class="ftco-heading-2">Instagram</h2>
		  <div class="thumb d-sm-flex">
				<a href="#" class="thumb-menu img" style="background-image: url(images/insta-1.jpg);">
				</a>
				<a href="#" class="thumb-menu img" style="background-image: url(images/insta-2.jpg);">
				</a>
				<a href="#" class="thumb-menu img" style="background-image: url(images/insta-3.jpg);">
				</a>
			</div>
			<div class="thumb d-flex">
				<a href="#" class="thumb-menu img" style="background-image: url(images/insta-4.jpg);">
				</a>
				<a href="#" class="thumb-menu img" style="background-image: url(images/insta-5.jpg);">
				</a>
				<a href="#" class="thumb-menu img" style="background-image: url(images/insta-6.jpg);">
				</a>
			</div>
		</div>
	  </div>
	</div>
	<div class="row">
	  <div class="col-md-12 text-center">

		<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
	  </div>
	</div>
  </div>
</footer>

{% endcomment %}

{% endblock %}

reservation/templates/Reservation/reservation.html
{% extends 'base.html' %}
{% load static %}
	
{% block body %}

	{% comment %}
    <section class="hero-wrap hero-wrap-2" style="background-image: url('images/bg_3.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">Reservation</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="base.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Reservation <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
	</section>
	{% endcomment %}
	
		<section class="ftco-section ftco-no-pt ftco-no-pb">
			<div class="container-fluid px-0">
				<div class="row d-flex no-gutters">
          <div class="col-md-6 order-md-last ftco-animate makereservation p-4 p-md-5 pt-5">
          	<div class="py-md-5">
	          	<div class="heading-section ftco-animate mb-5">
		          	<span class="subheading">Book a table</span>
		            <h2 class="mb-4">Make Reservation</h2>
				  </div>


				{% comment %}
	            <form action="#">
	              <div class="row">
	                <div class="col-md-6">
	                  <div class="form-group">
	                    <label for="">Name</label>
	                   {{form.name}}
	                  </div>
	                </div>
	                <div class="col-md-6">
	                  <div class="form-group">
	                    <label for="">Email</label>
	                    <input type="text" class="form-control" placeholder="Your Email">
	                  </div>
	                </div>
	                <div class="col-md-6">
	                  <div class="form-group">
	                    <label for="">Phone</label>
	                    <input type="text" class="form-control" placeholder="Phone">
	                  </div>
	                </div>
	                <div class="col-md-6">
	                  <div class="form-group">
	                    <label for="">Phone</label>
	                    <input type="text" class="form-control" id="book_date" placeholder="Date">
	                  </div>
	                </div>
	                <div class="col-md-6">
	                  <div class="form-group">
	                    <label for="">Time</label>
	                    <input type="text" class="form-control" id="book_time" placeholder="Time">
	                  </div>
	                </div>
	                <div class="col-md-6">
	                  <div class="form-group">
	                    <label for="">Person</label>
	                    <div class="select-wrap one-third">
	                      <div class="icon"><span class="ion-ios-arrow-down"></span></div>
	                      <select name="" id="" class="form-control">
	                        <option value="">Person</option>
	                        <option value="">1</option>
	                        <option value="">2</option>
	                        <option value="">3</option>
	                        <option value="">4+</option>
	                      </select>
	                    </div>
	                  </div>
	                </div>
	                <div class="col-md-12 mt-3">
	                  <div class="form-group">
	                    <input type="submit" value="Make a Reservation" class="btn btn-primary py-3 px-5">
	                  </div>
	                </div>
	              </div>
				</form>
				{% endcomment %}

				<form action="#" method="POST">
					{% csrf_token %}
					{{form}}

					<button type="submit" class="btn btn-primary">Submit</button>
				</form>

	          </div>
          </div>
          <div class="col-md-6 d-flex align-items-stretch pb-5 pb-md-0">
						<div id="map"></div>
					</div>
        </div>
			</div>
		</section>

{% endblock %} 